[package]
name = "dpscript-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
dpscript-analyzer = { path = "../dpscript-analyzer" }
dpscript-ast = { path = "../dpscript-ast" }
dpscript-core = { path = "../dpscript-core" }
dpscript-lexer = { path = "../dpscript-lexer" }
dpscript-parser = { path = "../dpscript-parser" }
dpscript-tokenizer = { path = "../dpscript-tokenizer" }

itertools = "0.14.0"
miette = { version = "7.6.0", features = ["fancy"] }
ron = "0.12.1"
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
facet = { version = "0.46.0", features = ["ordered-float"] }
ordered-float = { version = "5.3.0", features = ["serde"] }

tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

async-lsp = { version = "0.2.4", features = ["tokio"] }
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "fs", "macros", "time"] }
dashmap = "6.2.1"
tower = "0.5.3"
