[pack]
name = "example"
version = "0.1.0"
authors = ["RedstoneWizard08"]
description = "Example Project"

[version]
minecraft = "1.21.4"

[dependencies]
# This isn't actually necessary, but it's good as an example.
std = "../std"

[build]
output = "./out"
