[package]
name = "dpscript-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.1.1", features = ["display"] }
dpscript-core = { version = "0.1.0", path = "../dpscript-core" }
dpscript-tokenizer = { version = "0.1.0", path = "../dpscript-tokenizer" }
miette = "7.6.0"
thiserror = "2.0.18"
